"$schema" = "https://schemastore.netlify.app/netlify-toml.json"

[build]
environment = { NODE_OPTIONS = "--max-old-space-size=4096" }
command = "pnpm mk"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
targetPort = 1234
port = 1232
